name: Daily Task Check

on:
  repository_dispatch:
    types: [daily_task_check]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      secrets: write  # cho phép update GitHub Secrets
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install libsodium-wrappers axios

      - name: Set payload
        id: payload
        run: |
          if [ '${{ github.event_name }}' = 'repository_dispatch' ]; then
            echo 'data=${{ toJson(github.event.client_payload) }}' >> $GITHUB_OUTPUT
          else
            echo 'data={"date":"19-Apr-2026","members":[{"member":"Minh Thu","taskCount":1,"tasks":[{"task":"SN Outdated Content: 5. Temperature ~12.5 mins Illus (3.5)","type":"new"}],"tasksSummary":"1. SN Outdated Content"}]}' >> $GITHUB_OUTPUT
          fi

      - name: Run
        env:
          PAYLOAD: ${{ steps.payload.outputs.data }}
          LARK_APP_ID: ${{ secrets.LARK_APP_ID }}
          LARK_APP_SECRET: ${{ secrets.LARK_APP_SECRET }}
          LARK_REFRESH_TOKEN: ${{ secrets.LARK_REFRESH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: node src/index.js
